### PR TITLE
Added popstate event in order to support back/forward browser buttons.

### PR DESCRIPTION
**Pull request by taylorzane**
Previously the back/forward buttons did not work when attempting to navigate. 

I've tested in a personal application, and this seems to resolve those issues.

### CODE REVIEW

**Comment by TehShrike** [comment]
aah, this makes sense.

Do you think you could add a test in hash-brown-router that asserts this behavior with [`window.history.back()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/history)?  It would have to be added in https://github.com/TehShrike/hash-brown-router/blob/master/test/browser-test.js since the hash-location interface doesn't expose a `back` method.

Though... this is making me think that maybe it should.  Hmm.

**Comment by TehShrike** [comment]
hmm, changing the hash-location interface would be a feature or breaking change.  If we just want to make the back button work properly with sausage-router, this change is fine - there should just be a test in the hash-brown-router tests that simulates pressing the back button.

**Comment by taylorzane** [comment]
I can confirm that `history.back/forward()` triggers an update to the UI (just tested in the ASR demo you have).

**Comment by taylorzane** [comment]
I see, so you just want a unit test detailing this?

**Comment by TehShrike** [comment]
I added a test for the back button in https://github.com/TehShrike/hash-brown-router/commit/a5cd13180aab41e6369036f3d090f60ded28eb18 - it fails for the sausage-router before your change, but passes after your change.

**Comment by TehShrike** [comment]
Published as 1.1.1.

**Comment by taylorzane** [comment]
Awesome, thank you!

**Pull request merged**
